### ISSUE TITLE
ブランチ運用について

### ISSUE THREAD

**Issue by a4rcvv** [tuatmcc/tuat-mcc-web-site#15]
- `master`と`develop`(デフォルトブランチ)と`gh-pages`(Pages公開用ブランチ)があるけど、どこからブランチ生やしてどこにプルリク送ればいいですか？
- プルリクは勝手にマージしちゃってOK?

**Comment by a4rcvv** [comment]
これ個人的には
- `master`をデフォルトブランチ兼Pages公開用ブランチにしておく
- 記事作るときは`master`からブランチ(`docs/hogehoge`とかの名前)生やして`master`にマージ
- Nuxt側の機能拡張とかは`develop`にコミット(都度`feature/hogehoge`を`develop`から生やす)、いい感じになったら`master`にマージ

が良いんじゃないかなと思ってます (今からこの状況に持っていけるのか分からんが)

**Comment by takex5g** [comment]
現在は、developブランチで開発して、本番反映はmasterにマージという運用しています。
(自分がdevelopブランチに慣れてないからmasterで開発しがち)

現在の方式だと、記事更新するたびに毎回リリースブランチ立てる必要あって、面倒くさいとは思っていました。
masterブランチをデフォルトブランチにする懸念の一つ懸念としてあるのが、下書き中の記事をそのまま掲載する可能性がある事ですかね。でもそれ以上に記事更新の手軽さは追求するべき点なので、良さそう。

そこらへんお任せしても良いでしょうか..。

gh-pagesは、github actionsでデプロイするのに必要なブランチで、人間は触らなくていい部分っすね。

**Comment by a4rcvv** [comment]
ありがと〜〜

> gh-pagesは、github actionsでデプロイするのに必要なブランチで、人間は触らなくていい部分っすね。

あーーそうなのか、りょうかい (pagesなんもわからん)

> masterブランチをデフォルトブランチにする懸念の一つ懸念としてあるのが、下書き中の記事をそのまま掲載する可能性がある事ですかね。

「`docs/hogehoge`を`master`にマージしたら下書き解除」みたいな運用にできると思うので大丈夫そうな気がする

とりあえず`master`から`docs/hogehoge`を生やす感じで大丈夫だろうか

**Comment by takex5g** [comment]
オッケーオッケー

お願いします！！
